---
title: "George Mathew Lab 8C"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
Name: George Mathew
Reg No: 20BRS1176
Lab 8C

A. K means:

```{r}
# Loading data
data(iris)

# Structure
str(iris)
```

```{r}
# Installing Packages
#install.packages("ClusterR")
#install.packages("cluster")
```

```{r}
# Loading package
library(ClusterR)
library(cluster)
```

```{r}
# Removing initial label of
# Species from original dataset
iris_1 <- iris[, -5]
```

```{r}
# Fitting K-Means clustering Model
# to training dataset
set.seed(240) # Setting seed
kmeans.re <- kmeans(iris_1, centers = 3, nstart = 20)
kmeans.re
```

```{r}
# Cluster identification for
# each observation
kmeans.re$cluster
```

```{r}
# Confusion Matrix
cm <- table(iris$Species, kmeans.re$cluster)
cm
```

```{r}
# Model Evaluation and visualization
plot(iris_1[c("Sepal.Length", "Sepal.Width")])
plot(iris_1[c("Sepal.Length", "Sepal.Width")],
	col = kmeans.re$cluster)
plot(iris_1[c("Sepal.Length", "Sepal.Width")],
	col = kmeans.re$cluster,
	main = "K-means with 3 clusters")
```

```{r}
## Plotiing cluster centers
#kmeans.re$centers
#kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")]

# cex is font size, pch is symbol
#points(kmeans.re$centers[, c("Sepal.Length", "Sepal.Width")],
#	col = 1:3, pch = 8, cex = 3)
```

```{r}
## Visualizing clusters
y_kmeans <- kmeans.re$cluster
clusplot(iris_1[, c("Sepal.Length", "Sepal.Width")],
		y_kmeans,
		lines = 0,
		shade = TRUE,
		color = TRUE,
		labels = 2,
		plotchar = FALSE,
		span = TRUE,
		main = paste("Cluster iris"),
		xlab = 'Sepal.Length',
		ylab = 'Sepal.Width')
```
B. Hierarchical Clustering:
```{r}
# Installing the package
#install.packages("dplyr")
```

```{r}
# Loading package
library(dplyr)
```

```{r}
# Summary of dataset in package
head(mtcars)
```

```{r}
# Finding distance matrix
distance_mat <- dist(mtcars, method = 'euclidean')
distance_mat

# Fitting Hierarchical clustering Model
# to training dataset
set.seed(240) # Setting seed
Hierar_cl <- hclust(distance_mat, method = "average")
Hierar_cl

# Plotting dendrogram
plot(Hierar_cl)

# Choosing no. of clusters
# Cutting tree by height
abline(h = 110, col = "green")

# Cutting tree by no. of clusters
fit <- cutree(Hierar_cl, k = 3 )
fit

table(fit)
rect.hclust(Hierar_cl, k = 3, border = "green")
```

C. K medoids:
```{r}
#install.packages("factoextra")
```

```{r}
library(factoextra)
library(cluster)
```
```{r}
df <- USArrests

#remove rows with missing values
df <- na.omit(df)

#scale each variable to have a mean of 0 and sd of 1
df <- scale(df)

#view first six rows of dataset
head(df)
```

```{r}
fviz_nbclust(df, pam, method = "wss")
```
```{r}
#calculate gap statistic based on number of clusters
gap_stat <- clusGap(df,
                    FUN = pam,
                    K.max = 10, #max clusters to consider
                    B = 50) #total bootstrapped iterations

#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```

```{r}
#make this example reproducible
set.seed(1)

#perform k-medoids clustering with k = 4 clusters
kmed <- pam(df, k = 4)

#view results
kmed
```

```{r}
#plot results of final k-medoids model
fviz_cluster(kmed, data = df)
```



